# version: "3.9"
services:
  health-check:
    image: dmbtechdev/health-check:version1.0
    build:
      context: .
      dockerfile: Dockerfile-health
    restart: "always"
    depends_on:
      auth:
        condition: service_started
  auth:
    image: dmbtechdev/auth:latest:version1.0
    build:
      context: .
      dockerfile: Dockerfile-auth
    restart: "always"
    ports:
      - "50051:50051"