version: "3.11"
services:
  health-check:
    image: dmbtechdev/image:health-check.0.0.1
    build:
      context: .
      dockerfile: Dockerfile-health
    restart: "always"
    depends_on:
      auth:
        condition: service_started
  auth:
    image: dmbtechdev/image:auth.0.0.1
    build:
      context: .
      dockerfile: Dockerfile-auth
    container_name: auth
    restart: "always"
    ports:
      - "50051:50051"